### ISSUE TITLE
Unclear instructions for contributing

### ISSUE THREAD

**Issue by andela-kakpobome** [atomicman57/naija-state-local-government#1]
Very useful lib yo! 

However, as part of the instructions for contribution, you specify that one should use the commit convention `git checkout -b feature/feature-id/<3-4 word feature description>`, 
what `feature-id` are you referring to, is there a roadmap that we should be referencing?

**Comment by atomicman57** [comment]
Hi @andela-kakpobome, I've edited that. you can just do. 

> git checkout -b feature/<3-4 word feature description>

Thanks.

**Comment by akinjide** [comment]
This issue should be closed, looks resolved to me.

**Comment by Rebaiahmed** [comment]
What are the features that you want to implement in this package ?
