### ISSUE TITLE
Wrong LGA data for some states

### ISSUE THREAD

**Issue by ibesoft11** [atomicman57/naija-state-local-government#5]
I recently installed this package on a project I'm working on and during test I discovered that some states have incorrect LGA data. Example there is no local government like "Ikawuno" in Abia state and there is no "Ugep North" in Cross River state.

I suggest the entire `statesAndLocalGov.json` file is reviewed to ensure accurate information.
Thanks

**Comment by atomicman57** [comment]
Can you raise a PR with the modifications?

**Comment by atomicman57** [comment]
This is fixed now
